branch-defaults:
  master:
    environment: Metarating
    group_suffix: null
global:
  application_name: Metarating
  default_ec2_keyname: Metarating
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
